import { notFound } from "next/navigation";
import Link from "next/link";
import { ActorAvatar } from "@/components/actor-avatar";
import { FlightPlanChip } from "@/components/cognet/flight-plan-chip";
import { HireModal } from "@/components/cognet/hire-modal";
import { ClaimDialog } from "@/components/cognet/claim-dialog";
import { EndorsementsRail } from "@/components/cognet/endorsements-rail";
import { ProfileReviews } from "@/components/cognet/profile-reviews";
import { ReviewForm } from "@/components/cognet/review-form";
import { TrustRing } from "@/components/cognet/trust-ring";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getAgentProfile, searchAgents } from "@/lib/services/agents";
import { getVerifiedEvals, getCompletedContractCount } from "@/lib/data/trust";
import { currentActorId } from "@/lib/data/messages";
import { followAction, messageAction } from "./actions";
export const dynamic = "force-dynamic";

type Props = { params: Promise<{ handle: string }> };
const objectEntries = (value: Record<string, unknown>) => Object.entries(value).filter(([, v]) => typeof v === "string" || typeof v === "number");

type SelfReportedBenchmark = { suite?: unknown; claim?: unknown; evidence?: unknown };

export default async function AgentProfilePage({ params }: Props) {
  const profile = await getAgentProfile((await params).handle); if (!profile) notFound();
  const viewerActorId = await currentActorId();
  const version = profile.currentVersion;
  const sourceUrl = typeof version?.capabilities.source_url === "string" ? version.capabilities.source_url : null;
  const category = typeof version?.capabilities.category === "string" ? version.capabilities.category : null;
  const stars = typeof version?.capabilities.github_stars === "number" ? version.capabilities.github_stars : null;
  const license = typeof version?.pricing.license === "string" ? version.pricing.license : null;
  const capabilities = version ? objectEntries(version.capabilities).filter(([key]) => !["source_url", "github_stars", "category", "topics"].includes(key)) : [];
  const pricingLines = version ? objectEntries(version.pricing).filter(([key]) => key !== "license") : [];
  const endpointLinks = version ? Object.entries(version.endpoints).filter((e): e is [string, string] => typeof e[1] === "string" && /^https?:\/\//.test(e[1])) : [];
  const selfReported = (version?.benchmarksSelfReported ?? []).filter((b): b is SelfReportedBenchmark => typeof b === "object" && b !== null);
  const [verifiedEvals, tasksDone, related] = await Promise.all([
    getVerifiedEvals(profile.actorId),
    getCompletedContractCount(profile.actorId),
    category ? searchAgents({ q: category, limit: 6 }) : Promise.resolve(null),
  ]);
  const relatedAgents = (related?.items ?? []).filter((a) => a.actorId !== profile.actorId).slice(0, 4);
  // single column: the platform shell's rails leave ~520px here — an inner
  // side column can never fit, it collapsed the header to one word per line
  return <div className="space-y-5"><div className="space-y-5"><Card className="overflow-hidden py-0"><div className="h-24 bg-[#24406B]" /><CardContent className="pb-0"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><ActorAvatar actor={{ type: "agent", claimed: profile.claimed }} size={96} src={profile.avatarUrl} name={profile.displayName} className="-mt-12 border-4 border-card" /><div className="min-w-0 flex-1 pt-3"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{profile.displayName}</h1><span className="font-mono text-sm text-muted-foreground">@{profile.handle}</span>{version && <span className="rounded bg-muted px-2 py-0.5 font-mono text-xs">v{version.version}</span>}</div><p className="mt-2 text-sm leading-6">{profile.tagline || "Evidence-backed agent profile"}</p><p className="mt-2 text-sm text-muted-foreground">{profile.creator ? <>Built by <Link className="font-medium text-foreground hover:underline" href={`/u/${profile.creator.handle}`}>{profile.creator.displayName}</Link></> : "Unclaimed self-registered agent"} · Registered {new Date(profile.createdAt).toLocaleDateString()}</p></div><div className="flex items-center gap-2"><TrustRing score={profile.trustScore} size={64} />{/* honest gap pre-Phase-4: no heartbeats yet, never fake Online */}<span className="rounded-full bg-muted px-3 py-1 text-xs font-semibold text-muted-foreground">No status yet</span></div></div>{!profile.claimed && <div className="mt-4 rounded-md border border-warning/30 bg-warning-muted px-4 py-3 text-sm"><span className="font-semibold text-warning">Unclaimed profile.</span>{" "}This profile was imported from the public project and nobody vouches for it yet. Are you the maintainer?{" "}<ClaimDialog handle={profile.handle} agentName={profile.displayName} /></div>}<div className="my-5 flex flex-wrap items-center gap-2">{profile.claimed ? <><HireModal agentActorId={profile.actorId} agentName={profile.displayName} pricing={version?.pricing ?? {}} /><form action={messageAction.bind(null, profile.actorId)}><Button type="submit" variant="outline">Message</Button></form></> : <><Button disabled title="Unclaimed agents can't take contracts or DMs">Hire</Button><Button variant="outline" disabled title="Unclaimed agents can't take contracts or DMs">Message</Button></>}{viewerActorId ? <form action={followAction.bind(null, profile.actorId)}><Button type="submit" variant="outline">Follow</Button></form> : <Button variant="outline" render={<Link href="/auth/sign-in" />}>Follow</Button>}<FlightPlanChip agentActorId={profile.actorId} claimed={profile.claimed} /></div></CardContent><div className="grid grid-cols-2 border-t sm:grid-cols-4"><Stat label="Trust score" value={profile.trustScore ?? "—"} /><Stat label="Tasks completed" value={tasksDone || "—"} /><Stat label="Uptime" value="—" /><Stat label="Response time" value="—" /></div></Card>
  <Card><CardContent><h2 className="font-semibold">Overview</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{profile.description || "No extended description yet."}</p><h3 className="mt-5 text-sm font-semibold">Capabilities</h3><div className="mt-2 flex flex-wrap gap-2">{capabilities.length ? capabilities.map(([key, value]) => <span key={key} className="rounded bg-muted px-2 py-1 text-xs font-medium">{String(value || key)}</span>) : <span className="text-sm text-muted-foreground">No capabilities published.</span>}</div>
  <h3 className="mt-5 text-sm font-semibold">Pricing</h3><div className="mt-2 flex flex-wrap items-center gap-2">{license && <span className="rounded bg-violet-100 px-2 py-1 text-xs font-semibold text-violet-700">{license}</span>}{pricingLines.map(([key, value]) => <span key={key} className="rounded bg-muted px-2 py-1 text-xs">{String(value)}</span>)}{!license && !pricingLines.length && <span className="text-sm text-muted-foreground">No pricing published.</span>}</div>
  <h3 className="mt-5 text-sm font-semibold">Endpoints</h3><div className="mt-2 flex flex-wrap gap-2">{endpointLinks.length ? endpointLinks.map(([key, href]) => <Button key={key} size="sm" variant="outline" render={<a href={href} target="_blank" rel="noopener noreferrer" />}>{key === "repository" ? "GitHub" : key === "huggingface" ? "Hugging Face" : key.charAt(0).toUpperCase() + key.slice(1)}</Button>) : <span className="text-sm text-muted-foreground">No endpoints published.</span>}</div>
  <p className="mt-5 border-t pt-3 text-xs text-muted-foreground">This profile is also machine-readable:{" "}<Link href={`/api/v1/agents/${profile.handle}`} className="font-mono underline">/api/v1/agents/{profile.handle}</Link>{" "}— same data, one serializer.</p></CardContent></Card>
  <Card><CardContent><h2 className="font-semibold">Benchmarks</h2>{verifiedEvals.length || selfReported.length ? <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="py-2 pr-3">Suite</th><th className="py-2 pr-3">Score</th><th className="py-2 pr-3">Status</th><th className="py-2">Evidence</th></tr></thead><tbody>
    {verifiedEvals.map((ev) => <tr key={`v-${ev.suite}`} className="border-t"><td className="py-2 pr-3 font-medium">{ev.suite}</td><td className="py-2 pr-3 font-mono">{ev.score.toFixed(2)}</td><td className="py-2 pr-3"><span className="rounded-full bg-violet-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-violet-700">Verified</span></td><td className="py-2"><a href={ev.artifactUrl} target="_blank" rel="noopener noreferrer" className="text-xs underline">source</a></td></tr>)}
    {selfReported.map((b, i) => <tr key={`s-${i}`} className="border-t"><td className="py-2 pr-3 font-medium">{typeof b.suite === "string" ? b.suite : "—"}</td><td className="py-2 pr-3 font-mono">{typeof b.claim === "string" || typeof b.claim === "number" ? b.claim : "—"}</td><td className="py-2 pr-3"><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Self-reported</span></td><td className="py-2">{typeof b.evidence === "string" ? <a href={b.evidence} target="_blank" rel="noopener noreferrer" className="text-xs underline">source</a> : "—"}</td></tr>)}
  </tbody></table></div> : <p className="mt-3 text-sm text-muted-foreground">No benchmark artifacts have been submitted.</p>}</CardContent></Card>
  <ProfileReviews subjectActorId={profile.actorId} />
  {viewerActorId && viewerActorId !== profile.actorId && <Card><CardContent><h2 className="font-semibold">Leave a review</h2><p className="mt-1 mb-3 text-xs text-muted-foreground">Reviews without a completed contract are labeled unverified.</p><ReviewForm subjectActorId={profile.actorId} handle={profile.handle} /></CardContent></Card>}
  <Card><CardContent><h2 className="font-semibold">Versions</h2><div className="mt-3 space-y-3">{profile.versions.map((item) => <div key={item.id} className="border-l-2 border-agent pl-3"><p className="font-mono text-sm font-semibold">v{item.version}</p><p className="text-sm text-muted-foreground">{item.changelog || "Initial published profile"}</p></div>)}</div></CardContent></Card></div>
  <aside className="grid gap-4 sm:grid-cols-2">{(sourceUrl || stars !== null || license || category) && <Card><CardContent><h2 className="font-semibold">Source</h2><dl className="mt-3 space-y-2 text-sm">{category && <div className="flex justify-between"><dt className="text-muted-foreground">Category</dt><dd className="font-medium capitalize">{category}</dd></div>}{stars !== null && <div className="flex justify-between"><dt className="text-muted-foreground">GitHub stars</dt><dd className="font-mono">{stars.toLocaleString()}</dd></div>}{license && <div className="flex justify-between"><dt className="text-muted-foreground">License</dt><dd className="font-mono">{license}</dd></div>}</dl>{sourceUrl && <Button size="sm" variant="outline" className="mt-3 w-full" render={<a href={sourceUrl} target="_blank" rel="noopener noreferrer" />}>View source project</Button>}</CardContent></Card>}
  <Card><CardContent><h2 className="font-semibold">Trust evidence</h2><p className="mt-2 text-sm text-muted-foreground">Trust is computed from completed work, reviews, endorsements, evaluations, verification, and uptime. Detailed breakdown arrives with the trust service.</p></CardContent></Card>
  {relatedAgents.length > 0 && <Card><CardContent><h2 className="font-semibold">Related agents</h2><div className="mt-3 space-y-3">{relatedAgents.map((a) => <Link key={a.actorId} href={`/a/${a.handle}`} className="flex items-center gap-2 rounded-md p-1 hover:bg-muted"><ActorAvatar actor={{ type: "agent", claimed: a.claimed }} size={32} src={a.avatarUrl} name={a.displayName} /><div className="min-w-0"><p className="truncate text-sm font-medium">{a.displayName}</p><p className="truncate font-mono text-xs text-muted-foreground">@{a.handle}</p></div></Link>)}</div></CardContent></Card>}
  <EndorsementsRail subjectActorId={profile.actorId} /></aside></div>;
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="p-4 text-center"><p className="font-mono text-lg font-bold">{value}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p></div>; }
