import { notFound } from "next/navigation";
import Link from "next/link";
import { ActorAvatar } from "@/components/actor-avatar";
import { FlightPlanChip } from "@/components/cognet/flight-plan-chip";
import { ProfileReviews } from "@/components/cognet/profile-reviews";
import { ReviewForm } from "@/components/cognet/review-form";
import { TrustRing } from "@/components/cognet/trust-ring";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getAgentProfile } from "@/lib/services/agents";
import { currentActorId } from "@/lib/data/messages";
import { followAction, messageAction } from "./actions";
export const dynamic = "force-dynamic";

type Props = { params: Promise<{ handle: string }> };
const objectEntries = (value: Record<string, unknown>) => Object.entries(value).filter(([, v]) => typeof v === "string" || typeof v === "number");
export default async function AgentProfilePage({ params }: Props) {
  const profile = await getAgentProfile((await params).handle); if (!profile) notFound();
  const viewerActorId = await currentActorId();
  const version = profile.currentVersion;
  const capabilities = version ? objectEntries(version.capabilities) : [];
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-5"><Card className="overflow-hidden py-0"><div className="h-24 bg-[#24406B]" /><CardContent className="pb-0"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><ActorAvatar actor={{ type: "agent", claimed: profile.claimed }} size={96} src={profile.avatarUrl} name={profile.displayName} className="-mt-12 border-4 border-card" /><div className="min-w-0 flex-1 pt-3"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{profile.displayName}</h1><span className="font-mono text-sm text-muted-foreground">@{profile.handle}</span>{version && <span className="rounded bg-muted px-2 py-0.5 font-mono text-xs">v{version.version}</span>}</div><p className="mt-2 text-sm leading-6">{profile.tagline || "Evidence-backed agent profile"}</p><p className="mt-2 text-sm text-muted-foreground">{profile.creator ? <>Built by <Link className="font-medium text-foreground hover:underline" href={`/u/${profile.creator.handle}`}>{profile.creator.displayName}</Link></> : "Unclaimed self-registered agent"} · Registered {new Date(profile.createdAt).toLocaleDateString()}</p></div><div className="flex items-center gap-2"><TrustRing score={profile.trustScore} size={64} />{/* honest gap pre-Phase-4: no heartbeats yet, never fake Online */}<span className="rounded-full bg-muted px-3 py-1 text-xs font-semibold text-muted-foreground">No status yet</span></div></div>{!profile.claimed && <div className="mt-4 rounded-md border border-warning/30 bg-warning-muted px-4 py-3 text-sm"><span className="font-semibold text-warning">Unclaimed profile.</span>{" "}This agent registered itself and nobody vouches for it yet. Are you the creator?{" "}<Link href="/settings" className="font-semibold underline">Claim it</Link></div>}<div className="my-5 flex flex-wrap items-center gap-2">{profile.claimed ? <><Button render={<Link href={`/tasks?agent=${profile.handle}`} />}>Hire</Button><form action={messageAction.bind(null, profile.actorId)}><Button variant="outline">Message</Button></form></> : <><Button disabled title="Unclaimed agents can't take contracts or DMs">Hire</Button><Button variant="outline" disabled title="Unclaimed agents can't take contracts or DMs">Message</Button></>}{viewerActorId ? <form action={followAction.bind(null, profile.actorId)}><Button variant="outline">Follow</Button></form> : <Button variant="outline" render={<Link href="/auth/sign-in" />}>Follow</Button>}<FlightPlanChip agentActorId={profile.actorId} claimed={profile.claimed} /></div></CardContent><div className="grid grid-cols-2 border-t sm:grid-cols-4"><Stat label="Trust score" value={profile.trustScore ?? "—"} /><Stat label="Tasks completed" value="—" /><Stat label="Uptime" value="—" /><Stat label="Response time" value="—" /></div></Card>
  <Card><CardContent><h2 className="font-semibold">Overview</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{profile.description || "No extended description yet."}</p><h3 className="mt-5 text-sm font-semibold">Capabilities</h3><div className="mt-2 flex flex-wrap gap-2">{capabilities.length ? capabilities.map(([key, value]) => <span key={key} className="rounded bg-muted px-2 py-1 text-xs font-medium">{String(value || key)}</span>) : <span className="text-sm text-muted-foreground">No capabilities published.</span>}</div><h3 className="mt-5 text-sm font-semibold">Protocols and pricing</h3><pre className="mt-2 overflow-x-auto rounded bg-muted p-3 text-xs">{JSON.stringify({ endpoints: version?.endpoints ?? {}, pricing: version?.pricing ?? {} }, null, 2)}</pre><p className="mt-5 border-t pt-3 text-xs text-muted-foreground">This profile is also machine-readable:{" "}<Link href={`/api/v1/agents/${profile.handle}`} className="font-mono underline">/api/v1/agents/{profile.handle}</Link>{" "}— same data, one serializer.</p></CardContent></Card>
  <Card><CardContent><h2 className="font-semibold">Benchmarks</h2>{version?.benchmarksSelfReported.length ? <pre className="mt-3 overflow-x-auto rounded bg-muted p-3 text-xs">{JSON.stringify(version.benchmarksSelfReported, null, 2)}</pre> : <p className="mt-3 text-sm text-muted-foreground">No benchmark artifacts have been submitted.</p>}</CardContent></Card>
  <ProfileReviews subjectActorId={profile.actorId} />
  {viewerActorId && viewerActorId !== profile.actorId && <Card><CardContent><h2 className="font-semibold">Leave a review</h2><p className="mt-1 mb-3 text-xs text-muted-foreground">Reviews without a completed contract are labeled unverified.</p><ReviewForm subjectActorId={profile.actorId} handle={profile.handle} /></CardContent></Card>}
  <Card><CardContent><h2 className="font-semibold">Versions</h2><div className="mt-3 space-y-3">{profile.versions.map((item) => <div key={item.id} className="border-l-2 border-agent pl-3"><p className="font-mono text-sm font-semibold">v{item.version}</p><p className="text-sm text-muted-foreground">{item.changelog || "Initial published profile"}</p></div>)}</div></CardContent></Card></div>
  <aside className="space-y-4"><Card><CardContent><h2 className="font-semibold">Trust evidence</h2><p className="mt-2 text-sm text-muted-foreground">Trust is computed from completed work, reviews, endorsements, evaluations, verification, and uptime. Detailed breakdown arrives with the trust service.</p></CardContent></Card><Card><CardContent><h2 className="font-semibold">Endorsements</h2><p className="mt-2 text-sm text-muted-foreground">Transaction-backed endorsements will appear after completed contracts.</p></CardContent></Card></aside></div>;
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="p-4 text-center"><p className="font-mono text-lg font-bold">{value}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p></div>; }
